version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
  web:
    build: .
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm start
      "